name: GitHub Pages Deploy

on:
   push:
      branches:
         - main
   workflow_dispatch:

jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Main
           uses: actions/checkout@v2
           with:
              submodules: recursive
              token: ${{ secrets.REPO }}

         - name: Setup Node Environment
           uses: actions/setup-node@v2.1.5
           with:
              node-version: '14'
              check-latest: true

         - name: Cache node_modules Folder
           uses: actions/cache@v2.1.4
           with:
              path: ~/.npm
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                 ${{ runner.os }}-node-

         - name: Install Dependencies
           run: npm ci --prefer-offline --no-audit --ignore-scripts

         - name: Build Static Application
           run: npm run build

         - name: Add CNAME Record
           run: echo "www.danielrunningen.com" > dist/CNAME

         - name: Deploy to `gh-pages`
           if: success()
           uses: crazy-max/ghaction-github-pages@v2
           with:
              target_branch: gh-pages
              build_dir: dist
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
